const _HEADER_ROW_HEIGHT = 64;
const _FAB_HEIGHT = 54;

const _BLUR_INTENSITY = 12;
const _BLUR_START_OFFSET = 0.45;

const _PHOTO_TILTS = [-6, 4, -3, 5];

export { _BLUR_INTENSITY, _BLUR_START_OFFSET, _FAB_HEIGHT, _HEADER_ROW_HEIGHT, _PHOTO_TILTS };
