const DEFAULT_BLUR_INTENSITY = 50;
const MIN_BLUR_INTENSITY = 0;
const MAX_BLUR_INTENSITY = 100;
const DEFAULT_BLUR_REDUCTION_FACTOR = 4;
const DEFAULT_BLUR_ROUNDS = 2;
const DEFAULT_GAUSSIAN_BLUR_RADIUS = 0;
const MIN_ANDROID_SDK_FOR_GAUSSIAN_BLUR = 31;

export {
  DEFAULT_BLUR_INTENSITY,
  MIN_BLUR_INTENSITY,
  MAX_BLUR_INTENSITY,
  DEFAULT_BLUR_REDUCTION_FACTOR,
  DEFAULT_BLUR_ROUNDS,
  DEFAULT_GAUSSIAN_BLUR_RADIUS,
  MIN_ANDROID_SDK_FOR_GAUSSIAN_BLUR,
};
